### Numpy
- np.array数组：带顺序的字典
    - 数组的创建：np.array(),括号内可以是列表、元祖、数组、生成器
    - np.arange(start,stop,step)，类似range()，在给定间隔内返回均匀间隔的值,左闭右开区间
    - np.linspace(start,stop,num=50,endpoint=True)，返回在间隔start，stop上计算的num个均匀间隔的样本;
    - np.zeros(shape, dtype=float, order='C'):返回给定形状和类型的新数组，用零填充。
    - np.zeros_like(a, dtype=None, order='K', subok=True, shape=None) 具有与给定数组相同的形状和类型的零数组；
    - np.eye() 创建一个正方的N*N的单位矩阵，对角线值为1，其余为0
    - 数组形状：a.T/np.reshape(a, newshape, order='C')/np.resize(a, new_shape)/.resize(new_shape)/.reshape(newshape)
    - 复制：a.copy()
    - 类型转换：a.astype(np.XXX)
    - 数组堆叠:np.hstack((a,b))水平堆叠,元素不增加,np.vstack((a,b)),垂直堆叠，元素增加，np.stack((a,c),axis=0）
    - 数组拆分:np.hsplit(ary, indices_or_sections),np.vsplit,np.hsplit
    - 数组运算:+-*/,a.sum a.std a.min a.max a.var a.mean, axis计算
    - 索引：ar[1:3:2,1:3:2], N 行 N 列步长，多重索引ar[0][0]，布尔索引ar[i,:]，ar[:,j]， ar[ar > 5]
- 随机数:标准正太分布np.random.normal(size=(4,4));0-1随机浮点np.random.rand(),标准正太分布np.random.randn()；random.randint(low, high=None, size=None, dtype='l')
- 输入输出：os.chdir(),np.save(file directory,a),np.load(file),np.savetxt('array.txt',ar, delimiter=','),np.loadtxt('array.txt', delimiter=',')
### Pandas
- Series:带index的array，pd.Series(data=None,index=None,dtype=None,name=None,copy=False,fastpath=False)
    - Series创建：字典，数组，标量，s.index，s.values
    - 索引：位置下标，index,切片索引（默认下标，下标索引同序列），布尔型索引
    - 重新索引：s.reindex(index=None,fill_value = 0)
    - Series相加，相同标签自动对齐相加
    - 删除：s.drop(labels=None,axis=0,index=None,columns=None,level=None,inplace=False,errors='raise'）
    - 添加：直接通过下标索引/标签index赋值添加，通过.append()方法，直接添加一个数组
    - 修改：通过索引赋值
    - 排序：.sort_values，.sort_index，默认ascending=True, inplace=False
- np.Dataframe数据框：表格 pd.DataFrame(data=None,index: = None,columns: = None,dtype:= None）
    - DF创建：数组/list字典，Series字典,二维数组,字典列表,字典字典
    - 索引切片：df['a'] 直接索引列标签，df.loc[]索引行标签，df.iloc[]索引行数，布尔型索引多重索引和Series原理相同
    - 查看转置：.T ,
    - 添加与修改:行列索引赋值即可新建修改
    - 删除：del df[a]语句删除列,df.drop(labels=None,axis=0,inplace=False),axis=0删除行,1删除列
    - 对齐：DataFrame对象之间的数据相加自动按照列和索引（行标签）对齐
    - 排序：按值排序df.sort_values(['a','c']),ascending = True) ,.sort_index 
- 时间模块
    - import datetime as dt
        - datetime.date.today(),datetime.date(time),class 'datetime.date'
        - datetime.datetime(year,month,day),datetime.datetime.now(),class 'datetime.datetime',datetime的差为timedelta
        - datetime.timedelta(day,seconds),主要用作时间的加减法，相当于可被识别的时间“差值”
    - from dateutil.parser import parse
        - parse(timestr), 将str直接转化为日期格式
    - import pandas as pd
        - pd.Timestamp(time/timestr)
        - pd.to_datetime(time/timestr),pd.to_datetime(timelist)多个时间数据则转化为DatetimeIndex
        - pd.DatetimeIndex(timelist)生成DatetimeIndex
        - 以DatetimeIndex为index的Series，为TimeSries，时间序列如st = pd.Series(np.random.rand(len(rng)), index=rng)
        - pd.date_range(start,end,periods,freq='D',tz,normalize=False,name,closed)，生成日期范围DatetimeIndex
        - 时间频率转换，ts.asfreq('12H',method = 'ffill')) 
        - ts.shift() 正数：数值后移（滞后）；负数：数值前移（超前）
        - pd.Period(timesttamp,freq)创建时期
        - pd.period_range() 参数类似pd.data_range()
        - 时期-时间转换，ts1.to_period()，ts2.to_timestamp()
    - TimeSeries索引切片：
        - 时间序列索引，#支持各种时间字符串如ts['04/01/2020']
    - 重采样：.resample(freq)
        - 降采样：聚合，如何ts.resample('5D', closed = 'left').sum()
        - 升采样：填充，ts.resample('30T').asfreq()不填充，.ffill()向上，.bfill()向下
- 数值计算和统计基础
    - df.info(),df.describe()
    - axis\skipna,quantile,.skew,.kurt,.cumsum,cumprod,cummax,cummin，.value_counts()值计数
    - .unique()生成不重复的值为ndarray  .sort()排序， .isin()
    - 文本数据：.str进入，.str.count(),lower,.upper,len，startswith,endswith,strip,.replace,
        - split、rsplit,split(',', expand=True)
        - 字符串索引：str和字符串本身索引方式相同
    - 合并 merge、join：
        -连接：pd.merge(left,right,how= 'inner',on=None,left_on=None,right_on=None,copy: bool = True，suffixes=）
        -连接：left.join(right, on = 'key')
        -堆叠：pd.concat([s3,s4],axis=1,join='outer').sort_index()
        -修补：df2.combine_first(df1)根据index，df1的空值被df2替代,如果df2的index多于df1，则更新到df1上
        -修补：df1.update(df2)直接df2覆盖df1相同index位置数据
    - 去重替换：.duplicated .replace
    - 数据分组：df.groupby()
        - .get_group()提取分组后的组
        - .groups：将分组后的groups转为dict
        - 按照类型分组df.groupby(df.dtypes,axis=1)
        - 通过字典或者Series实现自定义分组，by_column = df.groupby(mapping, axis = 1)
        - 通过函数分组：print(df.groupby(len).sum())
        - 多函数计算：agg()，df.groupby('a').agg(['mean',np.sum])
        - 数据分组转换,.transform,如通过分组、合并，得到一个包含均值的Dataframe，df.groupby('key2').transform(np.mean)
        - 一般化Groupby方法：apply(func,parameter)
        - 数据透视表：pd.pivot_table(data, values=None, index=None, columns=None, aggfunc='mean', fill_value=None, margins=False, dropna=True, margins_name='All')
        - 交叉表：pd.crosstab(index, columns, values=None, rownames=None, colnames=None, aggfunc=None, margins=False, dropna=True, normalize=False)
    - 数据读取：delimiter：用于拆分的字符,index_col：指定某列为行索引，header：用做列名的序号，默认为0（取第一行）
        - pd.read_table(filepath,sep='\t',delimiter=None,header='infer',names=None,index_col=None)
        - data2 = pd.read_csv('data.csv',engine = 'python',encoding='utf-8')
        - data3 = pd.read_excel('data.excel',engine = 'python',encoding='utf-8')

In [27]:
## axis的理解：axis意味着最外层门是几个；如[[1,2],[3,4]]的axis为2
##axis=0的计算，表示对最外层[ ]里的最大单位块做块与块之间的运算,同时移除最外层[ ]：
#二维情形：axis=0代表在跨行（down),沿着每一列或行标签\索引值向下按列计算；axis=1代表跨列（across)，按行计算（想象成一个表格）
import numpy as np
a= np.array([1,2,3])    
print(a.sum(axis = 0))
b= np.array([[1,2],[3,4]])  ##最外层里的最大单位块为[1,2]和[3,4],运算sum得[[4,6]],移除最外层为[4,6]
print(b.sum(axis = 0))
## axis= 1表示对第二外层[]里的最大单位块做块与块之间的运算,同时移除第二外层[]：
print(b.sum(axis = 1))   #第二外层内为 1，2和3，4，分别运算得[[3,7]],移除最外层得[3,7]
## stack(arrays,axis=0)
c=np.array([4,5,6])    
print('*'*60) 
d=np.stack((a,c),axis=0)  # 合并数组为[[1, 2, 3], [4, 5, 6]]，最外层里的最大单位块为[1,2,3]和[3,4,5],直接堆叠；
e=np.stack((a,c),axis=1)  # 合并数组为[[1, 2, 3], [4, 5, 6]]，第二层里的最大单位块为1,2,3和3,4,5,直接堆叠；
print(d,'\n') 
print(e,'\n') 

6
[4 6]
[3 7]
************************************************************
[[1 2 3]
 [4 5 6]] 

[[1 4]
 [2 5]
 [3 6]] 



In [28]:
a=[[1],[2],[3]]
b=[[1],[2],[3]]
c=[[1],[2],[3]]
f=np.hstack((a,b,c))       #水平(按列顺序)把数组给堆叠起来
g=np.vstack((a,b,c))       #垂直(按行顺序)把数组给堆叠起来
print(f,'\n')  
print(g,'\n') 

[[1 1 1]
 [2 2 2]
 [3 3 3]] 

[[1]
 [2]
 [3]
 [1]
 [2]
 [3]
 [1]
 [2]
 [3]] 

